name: AWS quickstart deploy
run-name: ${{github.actor}} is deploying fintec quickstart
on:
  push:
    branches:
      - main
jobs:
  quickstart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install typescript
        run: npm install -g typescript

      - name: Install aws cdl core npm
        run: npm i @aws-cdk/core

      - name: install ts node
        run: npm i ts-node

      - name: install node
        run: npm i node

      - name: Configure AWS CDK
        run: npm install -g aws-cdk typescript

      - name: Bootstrap AWS CDK stack
        run: export CDK_NEW_BOOTSTRAP=1

      - name: Bootstrap AWS CDK stack pt2
        run: cdk bootstrap aws://${{secrets.AWS_ACCOUNT}}/${{secrets.AWS_REGION}}

      - name: Deploy quickstart
        run: cd quickstart-aws-fintech-blueprint

      - name: NPM install
        run: npm install

      - name: NPM deploy
        run: npm run build && cdk deploy
